void throwException(std::string msg);